# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/google/go-jsonnet
  rev: v0.20.0
  hooks:
    - id: jsonnet-format
    - id: jsonnet-lint